import { Client, Attendance, MembershipHistory } from '../types';
import { GymDB, getSavedSettings } from './db';

const CLIENTS_KEY = 'gym_clients_100';
const ATTENDANCE_KEY = 'gym_attendance_100';
const HISTORY_KEY = 'gym_membership_history_100';

// Helper to generate IDs
const generateId = () => Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);

// Helper to get relative dates
const getRelativeDateStr = (offsetDays: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

// Seed initial data if localStorage is empty
const seedDatabase = () => {
  if (localStorage.getItem(CLIENTS_KEY)) return;

  const mockClientsBase: any[] = [];
  const firstNames = ['Alex', 'Sarah', 'Bruce', 'Diana', 'Peter', 'Tony', 'Clark', 'Natasha', 'Steve', 'Barry', 'Wanda', 'Thor', 'John', 'Jane', 'Michael', 'Emily', 'David', 'Jessica', 'Daniel', 'Olivia', 'James', 'Mary', 'Robert', 'Patricia', 'William', 'Jennifer', 'Richard', 'Linda', 'Charles', 'Elizabeth'];
  const lastNames = ['Mercer', 'Connor', 'Wayne', 'Prince', 'Parker', 'Stark', 'Kent', 'Romanoff', 'Rogers', 'Allen', 'Maximoff', 'Odinson', 'Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis', 'Rodriguez', 'Martinez', 'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson', 'Thomas', 'Taylor', 'Moore'];
  
  for (let i = 1; i <= 100; i++) {
    const fn = firstNames[Math.floor(Math.random() * firstNames.length)];
    const ln = lastNames[Math.floor(Math.random() * lastNames.length)];
    const startOffset = -Math.floor(Math.random() * 180); // Up to 180 days ago
    const endOffset = startOffset + 30 * Math.floor(Math.random() * 12 + 1); // 1 to 12 months duration
    const isExpired = endOffset < 0;
    
    mockClientsBase.push({
      id: `c-${i}`,
      name: `${fn} ${ln}`,
      phone: `+1 (555) ${String(Math.floor(Math.random() * 1000)).padStart(3, '0')}-${String(Math.floor(Math.random() * 10000)).padStart(4, '0')}`,
      membership_start: getRelativeDateStr(startOffset),
      membership_end: getRelativeDateStr(endOffset),
      status: isExpired ? 'Expired' : 'Active',
      notes: `Autogenerated client #${i}. Randomly generated data.`,
      created_at: new Date(Date.now() + startOffset * 24 * 60 * 60 * 1000).toISOString(),
    });
  }

  const mockClients: Client[] = mockClientsBase.map((c, i) => ({
    ...c,
    membership_number: `MEM-${String(i + 1).padStart(3, '0')}`,
  }));

  // Seed Membership History
  const mockHistory: MembershipHistory[] = [];
  mockClients.forEach(c => {
    // Add original membership
    mockHistory.push({
      id: 'h-' + c.id + '-1',
      client_id: c.id,
      start_date: c.membership_start,
      end_date: c.membership_end,
      duration: 30, // Default 30 days
      renewed_on: c.created_at,
    });
  });

  // Seed 30 days of attendance
  const mockAttendance: Attendance[] = [];
  const today = new Date();

  for (let i = 0; i < 30; i++) {
    const d = new Date();
    d.setDate(today.getDate() - i);
    const dateStr = d.toISOString().split('T')[0];

    mockClients.forEach(client => {
      // Don't mark attendance before client was created or after membership end date
      const clientStart = new Date(client.membership_start);
      const clientEnd = new Date(client.membership_end);
      if (d < clientStart || d > new Date(clientEnd.getTime() + 24 * 60 * 60 * 1000)) {
        return;
      }

      // Check if client is active or was active at that date
      // Generate realistic attendance (random probability between 10% and 90% for each client)
      // We can seed the probability based on the client ID so it's consistent for that client
      const randomSeed = parseInt(client.id.split('-')[1]) || 50;
      const probability = 0.1 + ((randomSeed % 80) / 100);

      // Skip Sundays (gym closed)
      if (d.getDay() === 0) return;

      const isPresent = Math.random() < probability;
      mockAttendance.push({
        id: `att-${client.id}-${dateStr}`,
        client_id: client.id,
        date: dateStr,
        status: isPresent ? 'Present' : 'Absent',
        marked_at: new Date(d.getTime() + 9 * 60 * 60 * 1000).toISOString(), // 9 AM
      });
    });
  }

  localStorage.setItem(CLIENTS_KEY, JSON.stringify(mockClients));
  localStorage.setItem(ATTENDANCE_KEY, JSON.stringify(mockAttendance));
  localStorage.setItem(HISTORY_KEY, JSON.stringify(mockHistory));
};

// Initial Seed
seedDatabase();

// Local Storage DB implementation
export const localStorageDb: GymDB = {
  async getClients(): Promise<Client[]> {
    seedDatabase();
    const data = localStorage.getItem(CLIENTS_KEY);
    const clients: Client[] = data ? JSON.parse(data) : [];

    // Automatically recalculate Expired status relative to CURRENT date
    const todayStr = new Date().toISOString().split('T')[0];
    let changed = false;
    const updatedClients = clients.map(client => {
      const isExpired = client.membership_end && client.membership_end < todayStr;
      const calculatedStatus: 'Active' | 'Expired' = isExpired ? 'Expired' : 'Active';
      if (client.status !== calculatedStatus) {
        changed = true;
        return { ...client, status: calculatedStatus };
      }
      return client;
    });

    if (changed) {
      localStorage.setItem(CLIENTS_KEY, JSON.stringify(updatedClients));
      return updatedClients;
    }
    return clients;
  },

  async addClient(client): Promise<Client> {
    const clients = await this.getClients();
    const todayStr = new Date().toISOString().split('T')[0];
    const isExpired = client.membership_end && client.membership_end < todayStr;
    const status = isExpired ? 'Expired' : 'Active';

    const newClient: Client = {
      id: generateId(),
      membership_number: client.membership_number,
      name: client.name,
      phone: client.phone,
      membership_start: client.membership_start,
      membership_end: client.membership_end,
      status,
      notes: client.notes,
      created_at: new Date().toISOString(),
    };

    clients.push(newClient);
    localStorage.setItem(CLIENTS_KEY, JSON.stringify(clients));

    // Also write to membership history if dates are set
    if (client.membership_start && client.membership_end) {
      const start = new Date(client.membership_start);
      const end = new Date(client.membership_end);
      const diffTime = Math.abs(end.getTime() - start.getTime());
      const durationDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

      await this.addMembershipHistory({
        client_id: newClient.id,
        start_date: client.membership_start,
        end_date: client.membership_end,
        duration: durationDays,
      });
    }

    return newClient;
  },

  async updateClient(id, updatedFields): Promise<Client> {
    const clients = await this.getClients();
    const idx = clients.findIndex(c => c.id === id);
    if (idx === -1) throw new Error('Client not found');

    const oldClient = clients[idx];
    const newClientData = { ...oldClient, ...updatedFields };

    // Update status based on end date
    const todayStr = new Date().toISOString().split('T')[0];
    const isExpired = newClientData.membership_end && newClientData.membership_end < todayStr;
    newClientData.status = isExpired ? 'Expired' : 'Active';

    clients[idx] = newClientData;
    localStorage.setItem(CLIENTS_KEY, JSON.stringify(clients));

    // If membership dates were changed, append to history
    if (
      (updatedFields.membership_start && updatedFields.membership_start !== oldClient.membership_start) ||
      (updatedFields.membership_end && updatedFields.membership_end !== oldClient.membership_end)
    ) {
      const start = newClientData.membership_start;
      const end = newClientData.membership_end;
      if (start && end) {
        const startDate = new Date(start);
        const endDate = new Date(end);
        const diffTime = Math.abs(endDate.getTime() - startDate.getTime());
        const durationDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

        await this.addMembershipHistory({
          client_id: id,
          start_date: start,
          end_date: end,
          duration: durationDays,
        });
      }
    }

    return newClientData;
  },

  async deleteClient(id): Promise<boolean> {
    const clients = await this.getClients();
    const filtered = clients.filter(c => c.id !== id);
    localStorage.setItem(CLIENTS_KEY, JSON.stringify(filtered));

    // Cascade delete attendance and history
    const attData = localStorage.getItem(ATTENDANCE_KEY);
    if (attData) {
      const atts: Attendance[] = JSON.parse(attData);
      localStorage.setItem(ATTENDANCE_KEY, JSON.stringify(atts.filter(a => a.client_id !== id)));
    }

    const histData = localStorage.getItem(HISTORY_KEY);
    if (histData) {
      const hists: MembershipHistory[] = JSON.parse(histData);
      localStorage.setItem(HISTORY_KEY, JSON.stringify(hists.filter(h => h.client_id !== id)));
    }

    return true;
  },

  async getAttendance(date: string): Promise<Attendance[]> {
    const data = localStorage.getItem(ATTENDANCE_KEY);
    const atts: Attendance[] = data ? JSON.parse(data) : [];
    return atts.filter(a => a.date === date);
  },

  async getAttendanceRange(startDate: string, endDate: string): Promise<Attendance[]> {
    const data = localStorage.getItem(ATTENDANCE_KEY);
    const atts: Attendance[] = data ? JSON.parse(data) : [];
    return atts.filter(a => a.date >= startDate && a.date <= endDate);
  },

  async markAttendance(clientId: string, date: string, status: 'Present' | 'Absent'): Promise<Attendance> {
    const data = localStorage.getItem(ATTENDANCE_KEY);
    const atts: Attendance[] = data ? JSON.parse(data) : [];

    const existingIdx = atts.findIndex(a => a.client_id === clientId && a.date === date);

    if (existingIdx !== -1) {
      atts[existingIdx].status = status;
      atts[existingIdx].marked_at = new Date().toISOString();
      localStorage.setItem(ATTENDANCE_KEY, JSON.stringify(atts));
      return atts[existingIdx];
    } else {
      const newAtt: Attendance = {
        id: generateId(),
        client_id: clientId,
        date,
        status,
        marked_at: new Date().toISOString(),
      };
      atts.push(newAtt);
      localStorage.setItem(ATTENDANCE_KEY, JSON.stringify(atts));
      return newAtt;
    }
  },

  async getMembershipHistory(clientId: string): Promise<MembershipHistory[]> {
    const data = localStorage.getItem(HISTORY_KEY);
    const hists: MembershipHistory[] = data ? JSON.parse(data) : [];
    return hists.filter(h => h.client_id === clientId).sort((a, b) => b.renewed_on.localeCompare(a.renewed_on));
  },

  async addMembershipHistory(history): Promise<MembershipHistory> {
    const data = localStorage.getItem(HISTORY_KEY);
    const hists: MembershipHistory[] = data ? JSON.parse(data) : [];

    const newHistory: MembershipHistory = {
      id: generateId(),
      client_id: history.client_id,
      start_date: history.start_date,
      end_date: history.end_date,
      duration: history.duration,
      renewed_on: new Date().toISOString(),
    };

    hists.push(newHistory);
    localStorage.setItem(HISTORY_KEY, JSON.stringify(hists));
    return newHistory;
  },

  async processSelfCheckIn(params) {
    const settings = getSavedSettings();

    // 1. Verify Distance if gym location is set
    if (settings.gymLocationLat && settings.gymLocationLng) {
      const calculateDistance = (lat1: number, lon1: number, lat2: number, lon2: number) => {
        const R = 6371e3; // metres
        const φ1 = lat1 * Math.PI/180; // φ, λ in radians
        const φ2 = lat2 * Math.PI/180;
        const Δφ = (lat2-lat1) * Math.PI/180;
        const Δλ = (lon2-lon1) * Math.PI/180;

        const a = Math.sin(Δφ/2) * Math.sin(Δφ/2) +
                  Math.cos(φ1) * Math.cos(φ2) *
                  Math.sin(Δλ/2) * Math.sin(Δλ/2);
        const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));

        return R * c; // in metres
      };

      const dist = calculateDistance(params.latitude, params.longitude, settings.gymLocationLat, settings.gymLocationLng);
      if (dist > (settings.gymLocationRadius || 50)) {
        return { success: false, error: 'You are not inside the gym.' };
      }
    }

    // 2. Verify Membership
    const clients = await this.getClients();
    const client = clients.find(c => c.membership_number === params.membershipNumber);
    
    if (!client) {
      return { success: false, error: 'Invalid membership number.' };
    }

    if (client.status === 'Expired') {
      return { success: false, error: 'Your membership has expired.' };
    }

    // 3. Device Check
    const DEVICE_CHECKINS_KEY = 'gym_device_checkins';
    const rawDeviceCheckins = localStorage.getItem(DEVICE_CHECKINS_KEY);
    const deviceCheckins: any[] = rawDeviceCheckins ? JSON.parse(rawDeviceCheckins) : [];
    
    const todayStr = new Date().toISOString().split('T')[0];
    
    const todaysDeviceUsage = deviceCheckins.find(dc => 
      dc.deviceFingerprint === params.deviceFingerprint && 
      dc.date === todayStr
    );

    if (todaysDeviceUsage && todaysDeviceUsage.membershipNumber !== params.membershipNumber) {
      return { success: false, error: 'This device has already been used today to check in another member.' };
    }

    // 4. Duplicate Attendance Check
    const attendance = await this.getAttendance(todayStr);
    const alreadyCheckedIn = attendance.find(a => a.client_id === client.id);
    if (alreadyCheckedIn) {
      return { success: false, error: 'Attendance already marked today.' };
    }

    // 5. Mark Attendance & Device
    deviceCheckins.push({
      deviceFingerprint: params.deviceFingerprint,
      membershipNumber: params.membershipNumber,
      date: todayStr,
      time: new Date().toISOString(),
      lat: params.latitude,
      lng: params.longitude,
    });
    localStorage.setItem(DEVICE_CHECKINS_KEY, JSON.stringify(deviceCheckins));

    await this.markAttendance(client.id, todayStr, 'Present');

    return { 
      success: true, 
      details: {
        name: client.name,
        membership_number: client.membership_number,
        time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      } 
    };
  },

  async clearTestDeviceHistory(deviceFingerprint: string): Promise<void> {
    const DEVICE_CHECKINS_KEY = 'gym_device_checkins';
    const rawDeviceCheckins = localStorage.getItem(DEVICE_CHECKINS_KEY);
    if (rawDeviceCheckins) {
      let deviceCheckins: any[] = JSON.parse(rawDeviceCheckins);
      // Remove all records for this device
      deviceCheckins = deviceCheckins.filter(dc => dc.deviceFingerprint !== deviceFingerprint);
      localStorage.setItem(DEVICE_CHECKINS_KEY, JSON.stringify(deviceCheckins));
    }

    // Also clear today's attendance for testing purposes
    // We'll just wipe all attendance for today to be safe in test mode
    const todayStr = new Date().toISOString().split('T')[0];
    const rawAtt = localStorage.getItem(ATTENDANCE_KEY);
    if (rawAtt) {
      let atts = JSON.parse(rawAtt);
      atts = atts.filter((a: any) => a.date !== todayStr);
      localStorage.setItem(ATTENDANCE_KEY, JSON.stringify(atts));
    }
  }
};

